---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://dakoel.github.io/helm-charts'
    chart: adguard-home
    targetRevision: {{ .Values.adguard.targetRevision }}
    helm:
      values: |
        services:
          dns:
            type: LoadBalancer
        ingresses:
          http:
            enabled: true
            className: traefik
            hosts:
              - host: adguard.{{ .Values.domain }}
                paths:
                  - path: /
                    pathType: ImplementationSpecific
        bootstrapConfig:
          dns:
            rewrites:
              - domain: '*.{{ .Values.domain }}'
                answer: {{ .Values.clusterIp }}
  destination:
    server: {{ .Values.server }}
    namespace: adguard
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
