---
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  default.server: |
    jellyfin.{{ .Values.domain }} {
        hosts {
              {{ .Values.clusterIp }} jellyfin.{{ .Values.domain }}
              fallthrough
        }
    }
    prometheus.{{ .Values.domain }} {
        hosts {
              {{ .Values.clusterIp }} prometheus.{{ .Values.domain }}
              fallthrough
        }
    }
