---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://twin.github.io/helm-charts'
    chart: gatus
    targetRevision: {{ .Values.gatus.targetRevision }}
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - gatus.{{ .Values.domain }}
        persistence:
          enabled: true
          storageClassName: longhorn
        config:
          endpoints:
            - name: gatus
              url: https://gatus.{{ .Values.domain }}
              interval: 60s
              conditions:
                - "[STATUS] == 200"
              client:
                insecure: true
  destination:
    server: {{ .Values.server }}
    namespace: gatus
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
