---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: gitea
spec:
  encryptedData:
    password: {{ .Values.gitea.encryptedPassword }}
    username: {{ .Values.gitea.encryptedUsername }}
  template:
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: gitea
    type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://dl.gitea.io/charts'
    chart: gitea
    targetRevision: {{ .Values.gitea.targetRevision }}
    helm:
      values: |
        service:
          ssh:
            type: LoadBalancer
            port: 2222
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: gitea.{{ .Values.domain }}
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          size: {{ .Values.gitea.diskSize }}
          storageClass: longhorn
        gitea:
          admin:
            existingSecret: gitea-secret
  destination:
    server: {{ .Values.server }}
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
