---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://dakoel.github.io/helm-charts'
    chart: hello-world
    targetRevision: {{ .Values.helloWorld.targetRevision }}
  destination:
    server: {{ .Values.server }}
    namespace: hello-world
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
