---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyseerr
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://dakoel.github.io/helm-charts'
    chart: jellyseerr
    targetRevision: {{ .Values.jellyseerr.targetRevision }}
    helm:
      values: |
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: jellyseerr.{{ .Values.domain }}
              paths:
                - path: /
                  pathType: Prefix
        persistence:
          storageClass: longhorn
  destination:
    server: {{ .Values.server }}
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
