---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cifs-secret
  namespace: longhorn-system
spec:
  encryptedData:
    CIFS_PASSWORD: {{ .Values.longhorn.encryptedCifsPassword }}
    CIFS_USERNAME: {{ .Values.longhorn.encryptedCifsUsername }}
  template:
    metadata:
      creationTimestamp: null
      name: cifs-secret
      namespace: longhorn-system
    type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.longhorn.io'
    chart: longhorn
    targetRevision: {{ .Values.longhorn.targetRevision }}
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: traefik
          host: longhorn.{{ .Values.domain }}
        preUpgradeChecker:
          jobEnabled: false
        defaultBackupStore:
          backupTarget: cifs://{{ .Values.longhorn.backupTarget }}
          backupTargetCredentialSecret: cifs-secret
  destination:
    server: {{ .Values.server }}
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
