---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-stack-storage
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: {{ .Values.mediaStackStorageSize }}
