---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://dakoel.github.io/helm-homelab'
    chart: navidrome
    targetRevision: {{ .Values.navidrome.targetRevision }}
    helm:
      values: |
        ingress:
          main:
            enabled: true
            ingressClassName: traefik
            hosts:
              - host: navidrome.{{ .Values.domain }}
                paths:
                  - path: /
                    pathType: Prefix
        persistence:
          config:
            enabled: true
            storageClass: longhorn
          music:
            enabled: true
            storageClass: longhorn
            mountPath: /music
            size: {{ .Values.navidrome.musicDiskSize }}
  destination:
    server: {{ .Values.server }}
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
