---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sabnzbd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://dakoel.github.io/helm-homelab'
    chart: sabnzbd
    targetRevision: {{ .Values.sabnzbd.targetRevision }}
    helm:
      values: |
        ingress:
          main:
            enabled: true
            ingressClassName: traefik
            hosts:
              - host: sabnzbd.{{ .Values.domain }}
                paths:
                  - path: /
                    pathType: Prefix
        persistence:
          downloads:
            enabled: true
            mountPath: /media
            existingClaim: media-stack-storage
  destination:
    server: {{ .Values.server }}
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
