---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://dakoel.github.io/helm-charts'
    chart: uptime-kuma
    targetRevision: {{ .Values.uptimeKuma.targetRevision }}
    helm:
      values: |
        ingress:
          enabled: true
          className: traefik
          hosts:
            - host: uptimekuma.{{ .Values.domain }}
              paths:
                - path: /
                  pathType: Prefix
        volume:
          storageClassName: longhorn
  destination:
    server: {{ .Values.server }}
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
