---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-spotify
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://rubxkube.github.io/charts'
    chart: your-spotify
    targetRevision: {{ .Values.yourSpotify.targetRevision }}
    helm:
      values: |
        web:
          ingress:
            enabled: true
            hostName: yourspotify.{{ .Values.domain }}
            ingressClassName: traefik
  destination:
    server: {{ .Values.server }}
    namespace: your-spotify
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
